# Generated by Django 3.0.5 on 2020-04-20 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodels',
            name='duedate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todomodels',
            name='priority',
            field=models.CharField(choices=[('danger', 'high'), ('info', 'nomal'), ('success', 'low')], default='high', max_length=50),
            preserve_default=False,
        ),
    ]
